site_name: WWStay API Docs
site_description: API documentation of WWStay
repo_url: https://github.com/wwstay/docs
theme: readthedocs
site_favicon: favicon.ico

pages:
- ['index.md', 'Home']
- ['search/search-api.md', 'Search']
copyright: Copyright &copy; 2017, <a href="https://wwstay.com", target="_blank">WWStay</a>.
